### ISSUE TITLE
New messages do not show up

### ISSUE THREAD

**Issue by helje5** [lunatic-solutions/chat#2]
After I `/join #swift`ed a channel, I can send a message. It doesn't show up immediately though, looks like I have to re-join to get the message to show up.

**Comment by bkolobara** [comment]
Thanks for reporting this!

Can you just tell me what OS/terminal you are using and if you are accessing the US or EU server?

**Comment by helje5** [comment]
EU, macOS BS Terminal.app

**Comment by bkolobara** [comment]
The server was re-written in the meantime and I don't host any public instances anymore, so I will close this one.
